# Multi-line method chaining should be done with leading dots.
DotPosition:
  EnforcedStyle: leading

# Prefer Ruby 1.8 hash syntax { :a => 1, :b => 2 } over 1.9 syntax
# { a: 1, b: 2 }.
HashSyntax:
  EnforcedStyle: hash_rockets
